### PR TITLE
Make initial size configurable and tie max size to it

### PR DESCRIPTION
**Pull request by brushmate**
Proposal for #44

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@brushmate Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-pool&pullRequestId=45)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=r2dbc/r2dbc-pool&pullRequestId=45) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@brushmate Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=r2dbc/r2dbc-pool&pullRequestId=45)!

**Comment by mp911de** [comment]
Thanks for your contribution. Let's move the alignment about resizing `initialSize`/resizing `maxSize` depending on which of these options were configured to `ConnectionPoolConfiguration.Builder`. We can change `initialSize` and `maxSize` types to `Integer` and pre-initialize both with `null`. In `build()` we can use the validation and determine the the right `initialSize`/`maxSize`.

In `PoolingConnectionFactoryProvider`, we should leave the type-adapting parsing as the generic type is intended for API-based configuration and URL-based parsing delivers all options as `String`.

In fact, I started working on this one in parallel so I suggest leaving out `PoolingConnectionFactoryProvider` from this PR.

**Comment by brushmate** [comment]
I commited an update which contains only the `intialSize`/`maxSize` validation and defaults.

I was already thinking that there is a reason for the 'manual' option parsing but I could not figure out how `connectionFactoryOptions.getRequiredValue(MAX_SIZE)` could return anything else than an `Integer`.

**Comment by mp911de** [comment]
Thanks a lot, that's merged and polished now.

**Pull request merged**
